# Generated by Django 5.2.8 on 2025-11-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ("name",),
                "verbose_name": "Спикер",
                "verbose_name_plural": "Спикеры",
            },
        ),
        migrations.AlterModelOptions(
            name="speech",
            options={
                "ordering": ("event",),
                "verbose_name": "Презентация",
                "verbose_name_plural": "Презентации",
            },
        ),
        migrations.AlterField(
            model_name="participant",
            name="registered_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
