# Generated by Django 5.2 on 2025-11-26 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datacenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ("name",),
                "verbose_name": "Спикер",
                "verbose_name_plural": "Спикеры",
            },
        ),
        migrations.AlterModelOptions(
            name="speech",
            options={
                "ordering": ("event",),
                "verbose_name": "Презентация",
                "verbose_name_plural": "Презентации",
            },
        ),
    ]
