# Generated by Django 5.2 on 2025-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacenter", "0002_alter_speaker_options_alter_speech_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="registered_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
