# Generated by Django 5.2 on 2025-11-28 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datacenter", "0002_alter_speaker_options_alter_speech_options_and_more"),
        ("datacenter", "0003_alter_participant_registered_at"),
    ]

    operations = []
