# Generated by Django 5.2.8 on 2025-12-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0006_subscription_notify_new_events_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
